### ISSUE TITLE
Create services pages

### ISSUE THREAD

**Issue by aapeliv** [CustomProgrammingSolutions/CPS_gatsby#118]
Create pages describing in more detail what we can do for clients.

Maybe we could link to these from different blogs, and partition our set of offered services better, for instance to have people who come to look for ML stuff be easier routed to our ML services page, rather than be inundated with things about cryptography and kernel dev.

**Comment by shuttle1987** [comment]
Now that we have the page creation code in place we can talk about the page contents over in the content repo.
